;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-delete-forward
        eval-last-sexp
        evil-emacs-state
        evil-ex
        evil-first-non-blank
        evil-force-normal-state
        evil-insert
        evil-normal-state
        evil-open-above
        helm-M-x
        hydra-yank-pop/yank
        kill-sentence
        kmacro-end-macro
        kmacro-start-macro
        mc/mark-next-lines
        org-delete-char
        orgtbl-self-insert-command
        sp-backward-delete-char
        sp-forward-slurp-sexp
        sp-kill-sexp
        sp-raise-sexp
        transpose-words
        ))

(setq mc/cmds-to-run-once
      '(
        clojure-autotest
        evil-backward-char
        evil-delete-char
        evil-next-line
        evil-previous-line
        evil-search-word-forward
        hydra-yank-pop/lambda-n
        sp-kill-hybrid-sexp
        ))
