(defun leader (key) (read-kbd-macro (concat "C-, " key)))

(global-set-key (kbd "M-x") 'helm-M-x)
(define-key key-translation-map [?,] [(control ?,)])
(global-set-key (leader "SPC") 'maio/space-after-comma)
(global-set-key (leader "RET") 'maio/return-after-comma)
(global-set-key (leader "s") 'save-buffer)
(global-set-key (leader "w") 'save-buffer)
(global-set-key (leader "v") 'edit-init)
(global-set-key (leader "C-,") 'evil-buffer)
(global-set-key (leader "e") 'my-eval-defun)
(global-set-key (leader "g") 'magit-status)
(global-set-key (leader "k") 'kill-current-buffer)
(global-set-key (leader "t") 'helm-c-etags-select)
(global-set-key (leader "f") 'helm-projectile)
(global-set-key (leader "b") 'helm-mini)
(global-set-key (leader "a") 'ack-and-a-half)
(global-set-key (leader "1") 'delete-other-windows)
(global-set-key (kbd "C-<return>") 'midje-check-fact-near-point)
(global-set-key (kbd "C-w") 'evil-delete-backward-word)

(provide 'maio-keys)
