(require 'maio-leader)

(setq maio/leader-action-alist
      '((?w . force-save-buffer)
        (?, . other-buffer-or-window)
        (?b . helm-mini)
        (?k . kill-current-buffer)
        (?t . helm-c-etags-select)
        (?f . helm-git-find-files)
        (?r . helm-resume)
        (?s . helm-occur)
        (?v . find-config-file)
        (?e . my-eval-defun)
        (?n . maio-narrow-to-defun-clone)
        (?a . ack-and-a-half)
        (?1 . delete-other-windows)
        (?g . magit-status)))

(global-set-key (kbd "M-x") 'helm-M-x)
(evil-define-key 'normal clojure-mode-map (kbd "RET") 'midje-check-fact)
(define-key magit-status-mode-map (kbd "p") 'maio-git-submit)

(defun maio/electric-semicolon ()
  (interactive)
  (call-interactively 'move-end-of-line)
  (when (not (looking-back ";"))
    (insert ";")))

(defun maio/electric-space ()
  (interactive)
  (cond ((looking-back "(\\|{")
         (insert "  ")
         (backward-char))
        (t (insert " "))))

(defun maio/electric-return ()
  (interactive)
  (cond ((looking-back "(\\|{")
         (newline-and-indent)
         (call-interactively 'evil-open-above))
        (t (newline-and-indent))))

(provide 'maio-keys)
