(add-to-list 'load-path "~/.emacs.d/auto-complete")
(setq ac-ignore-case nil)
(setq ac-delay 0.1)
(setq ac-auto-show-menu nil)
(setq ac-quick-help-delay 0.5)
(require 'auto-complete-config)
(defun ac-common-setup ()
  (add-to-list 'ac-sources 'ac-source-words-in-all-buffer)
  (add-to-list 'ac-sources 'ac-source-yasnippet))
(ac-config-default)
(add-to-list 'ac-dictionary-directories "~/.emacs.d/ac-dict")
(add-to-list 'ac-modes 'eshell-mode)

(define-key ac-completing-map "\t" 'ac-complete)
(define-key ac-completing-map [tab] 'ac-complete)
(define-key ac-completing-map "\C-n" 'ac-next)
(define-key ac-completing-map "\C-p" 'ac-previous)

(provide 'maio-completion)
