set nocompatible
set wildignore=*~,*.o,*.log,*.pyc
set ignorecase smartcase
set tabstop=4
set shiftwidth=4
set expandtab
set smarttab
set autoindent
set smartindent
set wildmode=list:longest
set showbreak=
set scrolloff=10
set laststatus=2
set incsearch
set hlsearch
set noerrorbells
set visualbell
set wildmenu
set lcs=tab:»\ ,trail:•
set list
set shortmess=atI

if has("persistent_undo")
    set undofile
    set undodir=$HOME/.vim/undo
    set undolevels=1000
    set undoreload=10000
endif

set nobackup
set noswapfile

set runtimepath+=~/.vim/addons/vim-addon-manager
call vam#ActivateAddons(['Command-T','a.vim_-_Alternate_Files_quickly_.c',"xptemplate","fugitive","taglist","unimpaired","surround","repeat","mustache","tComment","VimClojure"])
let g:alternateExtensions_{'pm'} = "t"
let g:alternateExtensions_{'pl'} = "t"
let g:alternateExtensions_{'t'} = "pm,pl"
let g:alternateExtensions_{'body'} = "sql"
let g:alternateExtensions_{'m'} = "h"
let g:alternateExtensions_{'h'} = "m"
let g:alternateSearchPath = 'sfr:t,..'
let g:xptemplate_key = '<Tab>'
let g:xptemplate_vars = "SParg="
let g:xptemplate_brace_complete = '([{''"'
let g:loaded_sql_completion = 1
let g:ftplugin_sql_omni_key = 'X'

let vimclojure#FuzzyIndent=1
let vimclojure#HighlightBuiltins=1
let vimclojure#HighlightContrib=1
let vimclojure#DynamicHighlighting=1
let vimclojure#ParenRainbow=1
let vimclojure#WantNailgun=1
let vimclojure#NailgunClient = $HOME . "/bin/ng"

syntax on
set hidden
filetype plugin on
let mapleader=","
let maplocalleader = "\\"

" Visual Block mode is far more useful that Visual mode (so swap the
" commands)...
nnoremap v <C-V>
nnoremap <C-V> v
vnoremap v <C-V>
vnoremap <C-V> v
set virtualedit=block

cnoremap %% <C-R>=expand('%:h').'/'<cr>
cmap w!! w !sudo tee % >/dev/null

nnoremap // :TComment<CR>
vnoremap // :TComment<CR>

map - :A<CR>

" handle situation when yank buffer doesn't contain whole line - use normal paste
nmap p ]p
nmap P [p

nmap H ^
nmap L $
xmap H ^
xmap L $
nmap gp `[v`]
nmap <Leader><Leader> <C-^>

nmap "" ci"
nmap '' ci'

inoremap <C-j> <C-O>o
inoremap <C-k> <C-O>O
inoremap <C-l> <C-O>a

nnoremap <Space> @q
nnoremap <silent> <C-l> :noh<CR><C-l>
vnoremap <C-r> "hy:%s/<C-r>h//gc<left><left><left>
nnoremap Q gqap
vnoremap Q gq

map <Leader>e :e %%
map <leader>t :CommandTGit<cr>
map <leader>b :CommandTBuffer<cr>

map <Leader>w :w<CR>
map <Leader>. `.
imap <Leader>w <ESC>:w<CR>
map <Leader>go :only<CR>
map <Leader>gd :Gdiff<CR>
map <Leader>gs :Gstatus<CR>
map <Leader>gg yiw:Ggrep <C-r>0

" handle external paste
map <Leader>p :set invpaste paste?<CR>
imap <Leader>p <C-O>:set invpaste paste?<CR>
set pastetoggle=<Leader>p
autocmd InsertLeave * :set nopaste paste?

imap ZZ <ESC>:wq<CR>
imap jj <ESC>j
imap kk <ESC>k
imap lll <ESC>l
imap hh <ESC>h

imap <c-c> <esc>
xmap s <Plug>VSurround

set errorformat=%f:%l:\ error:\ %m,%f:%l:\ warning:\ %m
set guioptions=

colorscheme pablo
set background=dark
set t_Co=256

set guifont=Monaco:h15

let Tlist_Process_File_Always = 1
set statusline=[%l,%c]\ %<%f%=%([%{Tlist_Get_Tagname_By_Line()}]%)

autocmd BufReadPost * normal `"
autocmd BufNewFile,BufRead *.t,*.it :set ft=perl
autocmd BufNewFile,BufRead Makefile :set noexpandtab
autocmd BufNewFile,BufRead *.spec,*.body,*.sql :set filetype=plsql
autocmd Filetype perl :set equalprg=perltidy
autocmd Filetype php :set equalprg=perltidy
autocmd Filetype javascript :set equalprg=js_beautify.pl\ -
autocmd BufNewFile * :%!summon-file - % 2> /dev/null

" dict completion from dict files
set spellfile=~/.vim/dict.add
set dict+=~/.vim/dict.add
set complete=.,w,b,k


" conways
set formatoptions-=cro
set wrapmargin=2

" For Perl syntax...
set include=^\\s*use\\s\\+\\zs\\k\\+\\ze
set includeexpr=substitute(v:fname,'::','/','g')
set suffixesadd=.pm
execute 'set path+=' . substitute($PERL5LIB, ':', ',', 'g')
"Adjust keyword characters for Perlish identifiers...
set iskeyword+=$
set iskeyword+=%
set iskeyword+=@
set iskeyword-=,

highlight WHITE_ON_RED ctermfg=white ctermbg=red
call matchadd('WHITE_ON_RED', '_ref[ ]*[[{(]\|_ref[ ]*-[^>]')

set modelines=0

set title "Show filename in titlebar of window
set titleold=

set autoread
set backspace=indent,eol,start
set fileformats=unix,mac,dos
set noshowmode
" set timeout timeoutlen=300 ttimeoutlen=300

au BufReadPost quickfix setlocal number
                    \ | setlocal nowrap
                    \ | setlocal modifiable
                    \ | silent! %s/^[^|]*\//.../
                    \ | setlocal nomodifiable


"=====[ Tab handling ]======================================

set shiftround "Always indent/outdent to nearest tabstop

"== destroyallsoftware

function! ExtractVariable()
    let name = input("Variable name: ")
    if name == ''
        return
    endif
    " Enter visual mode (not sure why this is needed since we're already in
    " visual mode anyway)
    normal! gv

    " Replace selected text with the variable name
    exec "normal c" . name
    " Define the variable on the line above
    exec "normal! O" . name . " = "
    " Paste the original selected text to be the variable value
    normal! $p
    exec "normal! A;"
endfunction

function! InlineVariable()
    " Copy the variable under the cursor into the 'a' register
    " XXX: How do I copy into a variable so I don't pollute the registers?
    :normal "ayiw
    " It takes 4 diws to get the variable, equal sign, and surrounding
    " whitespace. I'm not sure why. diw is different from dw in this respect.
    :normal 4diw
    " Delete the expression into the 'b' register
    :normal "bdt;
    " Delete the remnants of the line
    :normal dd
    " Go to the end of the previous line so we can start our search for the
    " usage of the variable to replace. Doing '0' instead of 'k$' doesn't
    " work; I'm not sure why.
    normal k$
    " Find the next occurence of the variable
    exec '/\<' . @a . '\>'
    " Replace that occurence with the text we yanked
    exec ':.s/\<' . @a . '\>/' . @b
endfunction

vnoremap <leader>rv :call ExtractVariable()<cr>
nnoremap <leader>ri :call InlineVariable()<cr>

set switchbuf=useopen

