---

- name: tree
  homebrew: name=tree state=present

- name: ag grep
  homebrew: name=the_silver_searcher state=present

- name: fasd
  homebrew: name=fasd state=present

- name: imagemagick
  homebrew: name=imagemagick state=present

- name: aspell
  homebrew: name=aspell install_options="lang=en" state=present

- name: ctags-exuberant
  homebrew: name=ctags-exuberant state=present

- name: multitail
  homebrew: name=tree state=present

# aqe stuff
- name: jq
  homebrew: name=jq state=present

- name: s3cmd
  homebrew: name=s3cmd state=present

- name: md5sha1sum
  homebrew: name=md5sha1sum state=present

