---

- name: emacs
  package: name=emacs state=present
  become: yes
  tags: [Linux]

- name: checkout doom emacs
  git:
    repo: https://github.com/hlissner/doom-emacs
    dest: ~/.emacs.d
  register: checkout_result
  tags: [Darwin, Linux]

- name: doom emacs config
  file:
    src: "{{playbook_dir}}/../emacs/doom"
    dest: "~/.doom.d"
    state: link
  tags: [Darwin, Linux]

- name: config checksum
  shell: cat ~/.doom.d/* | md5sum > ~/.doom.d-checksum-new && diff -N ~/.doom.d-checksum ~/.doom.d-checksum-new || true
  register: diff_result
  tags: [Darwin, Linux]

- name: refresh doom emacs
  shell: ~/.emacs.d/bin/doom sync && cat ~/.doom.d-checksum-new > ~/.doom.d-checksum
  when: diff_result.stdout != "" or checkout_result.before != checkout_result.after
  tags: [Darwin, Linux]
