---

- name: add github keys to ~/.ssh/authorized_keys
  authorized_key:
    user: "{{ansible_user}}"
    state: present
    key: https://github.com/maio.keys
  tags: [Darwin, Linux]

- name: install keychain
  package: name=keychain state=present
  become: yes
  tags: [Linux]

- name: start keychain
  lineinfile: dest=~/.bashrc create=yes regexp='keychain' line='eval $(keychain --eval)'
  tags: [Linux]
