---

- name: "install linux package"
  package:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - curl
    - tree
    - ripgrep
    - silversearcher-ag
    - imagemagick
    - aspell
    - jq
    - npm
  tags: [Linux]

- name: install macos packate
  homebrew:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - tree
    - ripgrep
    - the_silver_searcher
    - imagemagick
    - aspell
    - jq
    - watch
  tags: [Darwin]
