---

- name: install linux packages
  package:
    name:
      - curl
      - tree
      - ripgrep
      - silversearcher-ag
      - imagemagick
      - aspell
      - jq
      - npm
      - vim
      - rsync
      - rdiff-backup
    state: present
  become: yes
  tags: [Linux]

- name: install global node packages
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - http-server
  tags: [Darwin, Linux]

- name: install macos packages
  homebrew:
    name:
      - curl
      - tree
      - ripgrep
      - the_silver_searcher
      - imagemagick
      - aspell
      - jq
      - watch
      - rsync
    state: present
  tags: [Darwin]
