---

- name: install packages
  package:
    name:
      - curl
      - tree
      - ripgrep
      - imagemagick
      - aspell
      - jq
      - npm
      - vim
      - rsync
      - parallel
    state: present
  become: yes
  tags: [Linux]

- name: install packages
  package:
    name:
      - curl
      - tree
      - ripgrep
      - imagemagick
      - aspell
      - jq
      - npm
      - vim
      - rsync
      - parallel
    state: present
  tags: [Darwin]

- name: install global node packages
  npm:
    global: yes
    name: "{{ item }}"
  with_items:
    - http-server
    - browser-sync
  tags: [Darwin, Linux]
  become: yes

- name: install macos packages
  homebrew:
    name:
      - curl
      - tree
      - ripgrep
      - the_silver_searcher
      - imagemagick
      - aspell
      - jq
      - watch
      - rsync
      - openssl
    state: present
  tags: [Darwin]

- name: OpenSSL PATH
  blockinfile:
    path: ~/.bashrc
    marker: "# {mark} Use OpenSSL from brew by default"
    block: |
      export PATH="/usr/local/opt/openssl@1.1/bin:$PATH"
  tags: [Darwin]
