#!/bin/bash
if [ "$TMUX" != "" ]; then
    tmux set -g status-left 'FAIL' > /dev/null
    tmux set -g status-fg red > /dev/null
    exit 1
fi

if [ -e "/usr/local/bin/growlnotify" ]; then
    growlnotify -d test --image "`dirname $0`/test-icons/failed.png" -m FAIL
    exit 1
fi
